name = "visual-studio-extension"
title = "Visual Studio Extension"

[constants]
product = "MongoDB Analyzer"
product-home-page = "https://github.com/mongodb/mongo-csharp-analyzer"
query-api = "MongoDB Query API"

driver-long = "MongoDB .NET driver"
driver-short = ".NET driver"
driver-version = 2.14
driver-docs = "https://mongodb.github.io/mongo-csharp-driver/{+driver-version+}/"
