name = "visual-studio-extension"
title = "MongoDB Analyzer"

[constants]
product = "MongoDB Analyzer"
product-home-page = "TODO: Insert homepage link when available"
product-source-repo = "https://github.com/mongodb/mongo-csharp-analyzer"
product-nuget-link = "https://www.nuget.org/packages/MongoDB.Analyzer"
product-package-name = "MongoDB.Analyzer"
product-version = "1.0"
product-version-full = "{+product-version+}.0"
product-settings-file-constant = "mongodb.analyzer.json"
product-jira = "https://jira.mongodb.org/browse/VS"

query-api = "MongoDB Query API"

driver-long = "MongoDB .NET driver"
driver-short = ".NET driver"
driver-version = "2.14"
driver-docs = "https://mongodb.github.io/mongo-csharp-driver/{+driver-version+}/"
